name: C++ CMake Build ⚒️

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: CMake Build

    # Github runner this will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Temporary install of dependencies
    - name: Install Ninja
      run: |
        sudo apt-get install \
          libgl1-mesa-dev \
          libx11-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libxrandr-dev \
          ninja-build
  
    # CMake configure with preset
    - name: Configure CMake
      working-directory: cpp
      run: cmake --preset clang-deb-ninja

    # Build with the preset
    - name: Build
      working-directory: cpp
      run: cmake --build --preset clang-deb-ninja

    # Execute the preset tests
    - name: Test
      working-directory: cpp
      run: ctest --preset clang-deb-ninja

