name: Nightly Build 🌃

on:
  schedule:
    - cron: '00 00 * * *'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Nightly Build

    # Github runner this will run on
    runs-on: ubuntu-latest

    steps:

    # Temporary install of dependencies
    - name: Nightly build
      run: echo "Running a nightly build. Good night!"
  
