name: Rust Build 🦀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Cargo Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      working-directory: rust
      run: cargo build --verbose
    - name: Say Hello
      run: echo "hello from pipeline"
    - name: Run tests
      working-directory: rust
      run: cargo test --verbose
